---
- name: apt | install dependencies
  apt:
    name: "{{ dvn_dependencies }}"
    state: present 

- name: apt | download .deb file
  apt:
    deb: "{{ dvn_apt_url }}"
    state: present

- name: systemd | upload service file
  template:
    src: systemd.j2
    dest: /lib/systemd/system/docker-volume-netshare.service
    mode: 0644
  notify: restart docker-volume-netshare

- name: systemd | start service
  systemd:
    name: docker-volume-netshare
    state: started
    enabled: yes

- name: docker volume | create netshare volume
  docker_volume:
    name: "{{ dvn_volume_config.name }}"
    driver: "{{ dvn_volume_config.driver }}"
    driver_options: "{{ dvn_volume_config.driver_options }}"
    state: present
  when: dvn_volume_config|length>0
