---
name: test-build

on:
  repository_dispatch: 
    types: test-build
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Prepare 
        shell: bash
        run: |
          pip install --upgrade yamllint==1.25.0 ansible-lint==4.2.0
      - name: Run tests
        shell: bash
        run: |
          yamllint .
          ansible-lint
